### ISSUE TITLE
Slicer not working

### ISSUE THREAD

**Issue by delijati** [DataBrewery/cubes-examples#8]
```
../env/bin/slicer serve slicer.ini
ConfigParser.NoSectionError: No section: 'model'
````

**Comment by mrsarm** [comment]
Same problem with both examples.

I created an environment with Python 2.7 and the packages specified in ``requirements.pip``.

Full error:

    Traceback (most recent call last):
      File "/projects/cubes/cubes-examples/env2.7/bin/slicer", line 326, in <module>
        args.func(args)
      File "/projects/cubes/cubes-examples/env2.7/bin/slicer", line 151, in run_server
        cubes.server.run_server(config)
      File "/projects/cubes/cubes-examples/env2.7/local/lib/python2.7/site-packages/cubes/server/slicer.py", line 224, in run_server
        application = Slicer(config)
      File "/projects/cubes/cubes-examples/env2.7/local/lib/python2.7/site-packages/cubes/server/slicer.py", line 100, in __init__
        self.context = create_slicer_context(config)
      File "/projects/cubes/cubes-examples/env2.7/local/lib/python2.7/site-packages/cubes/workspace.py", line 58, in create_slicer_context
        model_path = config.get("model", "path")
      File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
        raise NoSectionError(section)
    ConfigParser.NoSectionError: No section: 'model'

**Comment by mrsarm** [comment]
It's a environment issue. Now when I tested both examples with the environment specified in https://raw.githubusercontent.com/DataBrewery/cubes-heroku-demo/master/requirements.txt works!

The "procurements" Flask example only works with Chrome. It doesn't working with latest Firefox browser.

**Comment by JesseYan** [comment]
Same problem with both examples.

my environment is `virtualenv`+`python2.7`, both examples can not run, error like:

```shell

(cubes-examples-venv) ➜  webshop git:(master) ✗ slicer serve slicer.ini
Traceback (most recent call last):
  File "/Users/jesse/workspace/venv/cubes-examples-venv/bin/slicer", line 326, in <module>
    args.func(args)
  File "/Users/jesse/workspace/venv/cubes-examples-venv/bin/slicer", line 151, in run_server
    cubes.server.run_server(config)
  File "/Users/jesse/workspace/venv/cubes-examples-venv/lib/python2.7/site-packages/cubes/server/slicer.py", line 224, in run_server
    application = Slicer(config)
  File "/Users/jesse/workspace/venv/cubes-examples-venv/lib/python2.7/site-packages/cubes/server/slicer.py", line 100, in __init__
    self.context = create_slicer_context(config)
  File "/Users/jesse/workspace/venv/cubes-examples-venv/lib/python2.7/site-packages/cubes/workspace.py", line 58, in create_slicer_context
    model_path = config.get("model", "path")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'model'
```
